name: 'Build LSPD'
description: 'Build LSPD and upload the build artifacts.'
runs:
  using: 'composite'
  steps:
    - name: git checkout
      uses: actions/checkout@v4

    - name: get commit id
      run: |
        echo "COMMIT=$(git describe --tags --dirty)" >> $GITHUB_ENV
        echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: build lspd
      env:
        PKG: github.com/breez/lspd
      run: |
        go get ${PKG}
        go build -v -trimpath -o lspd -ldflags "-s -w -X ${PKG}/build.Commit=${COMMIT} -X ${PKG}/build.CommitHash=${COMMIT_HASH}" ${PKG}

    - name: build cln plugin
      env:
        PKG: github.com/breez/lspd
      run: |
        go get ${PKG}/cln_plugin/cmd
        go build -v -trimpath -o lspd_plugin -ldflags="-s -w -X ${PKG}/build.Commit=${COMMIT} -X ${PKG}/build.CommitHash=${COMMIT_HASH}" ${PKG}/cln_plugin/cmd

    - name: upload lspd artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          lspd
          lspd_plugin
